version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g pnpm@9.10.0
      - pnpm config set store-dir ~/.pnpm-store
      - node -v
      - pnpm -v
  build:
    commands:
      - pnpm install --ignore-scripts --frozen-lockfile
      - openssl genrsa -out private_key.pem 2048
      - openssl rsa -pubout -in private_key.pem -out public_key.pem
      - ENCODED_PUBLIC_KEY=$(cat public_key.pem | awk '{printf "%s\\n", $0}')
      - echo ${ENCODED_PUBLIC_KEY}
      - pnpm run secret:encodekey --stage=production
      - pnpm run secret:private --stage=production
      - rm -f private_key.pem public_key.pem
      - pnpm run unlock --stage=production --print-logs
      - pnpm run refresh --stage=production --print-logs
      - pnpm run deploy --stage=production --print-logs
cache:
  paths:
    - ~/.pnpm-store/**/*
