version: 0.2
phases:
  install:
    commands:
      # pnpm系
      - curl https://get.volta.sh | bash
      - export VOLTA_HOME=$HOME/.volta
      - export PATH=$VOLTA_HOME/bin:$PATH
      - echo $VOLTA_HOME
      - echo $PATH
      - volta -v
      - volta install node@20.13.1
      - node -v
      # - volta install pnpm@9.10.0
      - volta install pnpm
      - export VOLTA_FEATURE_PNPM=1
      - hash -r
      - which pnpm
      - pnpm -v
      - pnpm config set store-dir ~/.pnpm-store
  build:
    commands:
      - pnpm install --ignore-scripts --frozen-lockfile
      - openssl genrsa -out private_key.pem 2048
      - openssl rsa -pubout -in private_key.pem -out public_key.pem
      - ENCODED_PUBLIC_KEY=$(cat public_key.pem | awk '{printf "%s\\n", $0}')
      - echo ${ENCODED_PUBLIC_KEY}
      - pnpm run secret:encodekey --stage=production
      - pnpm run secret:private --stage=production
      - rm -f private_key.pem public_key.pem
      - pnpm run unlock --stage=production --print-logs
      - pnpm run refresh --stage=production --print-logs
      - pnpm run deploy --stage=production --print-logs
cache:
  paths:
    - ~/.pnpm-store/**/*
