version: 0.2
phases:
  install:
    commands:
      # pnpm系
      - curl https://get.volta.sh | bash
      - export VOLTA_HOME=$HOME/.volta
      - export PATH=$VOLTA_HOME/bin:$PATH
      - volta --version
      # - volta install node@20.13.1
      # - volta install pnpm@9.10.0
      # Volta 初期化 & Node.js インストール
      - $VOLTA_HOME/bin/volta install node@20.13.1
      # 🟡 VoltaでインストールしたNodeを有効にするための再読み込み
      - hash -r
      - which node
      - node -v
      - which npm
      - npm -v
      # pnpm のインストール
      - npm install -g pnpm@9.10.0
      - pnpm -v
      - export VOLTA_FEATURE_PNPM=1
      - node -v
      - pnpm -v
      - pnpm config set store-dir ~/.pnpm-store
  build:
    commands:
      - pnpm install --ignore-scripts --frozen-lockfile
      - openssl genrsa -out private_key.pem 2048
      - openssl rsa -pubout -in private_key.pem -out public_key.pem
      - ENCODED_PUBLIC_KEY=$(cat public_key.pem | awk '{printf "%s\\n", $0}')
      - pnpm run secret ENCODED_KEY "$ENCODED_PUBLIC_KEY" --stage=production
      - pnpm run secret PRIVATE_KEY < ./private_key.pem --stage=production
      - rm -f private_key.pem public_key.pem
      - pnpm run unlock --stage=production --print-logs
      - pnpm run refresh --stage=production --print-logs
      - pnpm run deploy --stage=production --print-logs
cache:
  paths:
    - ~/.pnpm-store/**/*
